title:              Junha's space
email:              junha4304@gmail.com
description:        Welcome to junha's workspace!
author:             junha
baseurl:            " "
url:                "https://junha-lee.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    "https://github.com/junha-lee"
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
